### ISSUE TITLE
RBAC error when creating local volume

### ISSUE THREAD

**Issue by brainfunked** [openshift/local-storage-operator#52] opened 2019-10-14 02:47 UTC
Just deployed a local-storage-operator on a three node master-only virtualized cluster created by dev-scripts. Attached a qcow2 image as the block device sdf to master-0. I then created a local volume. This resulted in localvolume/elastic being created, but with the following error:

```error syncing local storage: error applying pv cluster role binding local-storage-provisioner-pv-binding: clusterrolebindings.rbac.authorization.k8s.io "local-storage-provisioner-pv-binding" is forbidden: user "system:serviceaccount:local-storage:local-storage-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:local-storage" "system:authenticated"]) is attempting to grant RBAC permissions not currently held: {APIGroups:["events.k8s.io"], Resources:["events"], Verbs:["create" "patch" "update"]}```

This is what's visible in the event stream: https://i.imgur.com/6CaEcSw.png

All the yaml files used are in this gist: https://gist.github.com/brainfunked/8cc3609c6845bf4829e03b4f7d497de4

**Comment by brainfunked** [comment] 2019-10-14 03:09
```
[root@localhost ~]# oc get all -n local-storage -o wide
NAME                                          READY   STATUS    RESTARTS   AGE   IP            NODE       NOMINATED NODE   READINESS GATES
pod/local-storage-operator-7759795457-7pjsf   1/1     Running   0          97m   10.128.0.40   master-2   <none>           <none>

NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE   SELECTOR
service/local-storage-operator   ClusterIP   172.30.11.149   <none>        60000/TCP   97m   name=local-storage-operator

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS               IMAGES                                                   SELECTOR
deployment.apps/local-storage-operator   1/1     1            1           97m   local-storage-operator   quay.io/openshift/origin-local-storage-operator:latest   name=local-storage-operator

NAME                                                DESIRED   CURRENT   READY   AGE   CONTAINERS               IMAGES                                                   SELECTOR
replicaset.apps/local-storage-operator-7759795457   1         1         1       97m   local-storage-operator   quay.io/openshift/origin-local-storage-operator:latest   name=local-storage-operator,pod-template-hash=7759795457
```

**Comment by brainfunked** [comment] 2019-10-14 03:50
The above installation was done on a deployment created a few hours ago. Looks like it is running 4.3. This could be part of the problem because the local-storage-operator is showing up as version 4.2.

```oc version
Client Version: 4.3.0-0.ci-2019-10-12-191756
Server Version: 4.3.0-0.okd-2019-10-12-211448
Kubernetes Version: v1.16.0-beta.2+d1ee342
```

**Comment by brainfunked** [comment] 2019-10-25 06:18
This issue is addressed when the cluster-admin role is assigned to the local-storage-operator service account:

```
oc adm policy add-cluster-role-to-user cluster-admin -z local-storage-operator -n local-storage
```

This step should either be applied by default during installation or be explicitly documented.

Also, there's a local-storage-admin service account created by the CSV. What's the purpose of this SA?

**Comment by huffmanca** [comment] 2020-04-19 00:26
@brainfunked ,

This was a known issue that was addressed via https://bugzilla.redhat.com/show_bug.cgi?id=1766856 . This issue should be resolved, and I cannot reproduce it. Is it possible to try reproducing this issue, or closing it if it's no longer a problem?

**Comment by brainfunked** [comment] 2020-04-28 14:27
Will be doing a deployment using LSO in a couple of days. I'll verify if this issue is still present.

**Closed** 2020-12-07 21:58 UTC
Labels: lifecycle/rotten
